# Generated by Django 5.0.6 on 2024-09-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_stripe_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "interval",
                    models.CharField(
                        choices=[("month", "Monthly"), ("year", "Yearly")],
                        default="month",
                        max_length=120,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=99.99, max_digits=10),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=-1, help_text="Ordering on Django pricing page"
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=True, help_text="Featured on Django pricing page"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
    ]
