# Generated by Django 5.0.6 on 2024-09-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_subscription_featured_subscription_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["order", "featured", "-updated"],
                "permissions": [
                    ("advanced", "Advanced Perm"),
                    ("pro", "Pro Perm"),
                    ("basic", "Basic Perm"),
                    ("basic_ai", "Basic AI Perm"),
                ],
            },
        ),
    ]
