# Generated by Django 5.0.6 on 2024-09-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={
                "ordering": ["subscription__order", "order", "featured", "-updated"]
            },
        ),
    ]
