name: 1 - Hello World GitHub actions

on:
  workflow_dispatch: # Manually trigger the workflow
  # schedule:
  #   - cron: '30 15 * * *' # https://crontab.guru/
  # push: # git push
  #   branch:
  #     - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo "hello"